Request money on Sandbox if balance zero. (bunq/tinker_java#7)
bunq/tinker_java pull request #8
Opened 2018-04-04 21:55 UTC by JordyHeemskerk

2018-04-05 11:40 UTC, OGKevin requested changes
Minor changes.

2018-04-05 11:40 UTC, OGKevin commented on src/main/java/com/bunq/tinker/libs/BunqLib.java
> +    if (ApiEnvironmentType.SANDBOX.equals(environmentType)
Logic can be extracted in its own separate method.

2018-04-05 11:40 UTC, OGKevin commented on src/main/java/com/bunq/tinker/libs/BunqLib.java
> +    this.requestSpendingMoneyIfNeeded();
TODO: bunq/sdk_java#79

after sdk update.

2018-04-12 12:17 UTC, JordyHeemskerk commented
@OGKevin moving UserContext refresh to new issue. Implemented comments.

2018-04-12 17:16 UTC, OGKevin requested changes
2 small little things.

2018-04-12 17:16 UTC, OGKevin commented on src/main/java/com/bunq/tinker/libs/BunqLib.java
> +        // We don't care about being interrupted.
Meh this is risky and makes debug hard :D. At least print the error message :P

2018-04-12 17:16 UTC, OGKevin commented on src/main/java/com/bunq/tinker/libs/BunqLib.java
> +        Thread.sleep(2000);
magic

2018-04-12 17:18 UTC, OGKevin requested changes
1 small change.

2018-04-12 17:18 UTC, OGKevin commented on src/main/java/com/bunq/tinker/libs/BunqLib.java
> +        // We don't care about being interrupted.
This is risky and makes debug hard. So just print the error message instead of completely ignoring it :D

2018-04-16 08:30 UTC, JordyHeemskerk commented
@OGKevin

2018-04-16 09:11 UTC, OGKevin approved these changes
LGTM

2018-04-16 09:11 UTC, merged

2018-04-16 09:11 UTC, OGKevin commented
@andrederoos